### ISSUE TITLE
[TASK] create_zarr_structure shoud not depend on `path_dict_channels`

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#101]
instead compute it on the fly from filenames

**Comment by tcompa** [comment]
That file includes additional information that is not available from the filenames, e.g.
```
{
    "A01_C01": {
        "label": "DAPI",
        "colormap": "00FFFF",
        "start": 0,
        "end": 700
    },
    "A01_C02": {
        "label": "nanog",
        "colormap": "FF00FF",
        "start": 0,
        "end": 180
    },
    "A02_C03": {
        "label": "Lamin B1",
        "colormap": "FFFF00",
        "start": 0,
        "end": 1500
    }
}
```
where only the `A01_C01` names can be parsed from filenames.

**Comment by jacopo-exact** [comment]
ok, then it is to be moved to the default parameters of the task itself, to embed in the manifest

**Comment by jluethi** [comment]
The logic being: Users should be able to specify channel names, channel colors and optionally also channel "rescaling-values" (metadata relevant to visualization).

**Comment by tcompa** [comment]
This has been fixed for a while, in `server` branch and its subbranches.
The `create_zarr_structure` task currently takes a `channel_parameters` dictionary as an input.

Closing this issue.
