### ISSUE TITLE
Try/expose several cellpose models, for labeling

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#110]
> Finally, we may want to switch the cellpose model being used. Currently, we use the nuclei model (see here: https://github.com/fractal-analytics-platform/fractal/blob/6fc6a7b140548f9c056c89ada240c04202bf8f53/fractal/tasks/image_labeling_whole_well.py#L93). It will be interesting to try a few of their default models (e.g. the cyto2 model may perform better on this task) :slightly_smiling_face: . If it makes a difference, model choice could be exposed to the user

**Comment by jluethi** [comment]
Available options are: 'cyto', 'nuclei' and 'cyto2'.
(anything else would not work)

**Comment by tcompa** [comment]
Just as a test, I ran a `{1 well, 2x2 sites, 10 Z planes}` example with arbitrary `model_type`'s: `cyto` for the per-FOV labeling, and `cyto2` for the per-well labeling.

The runtime is a bit different than for `nuclei` (it is actually a bit longer, in this case, with single FOVs labeled in about 10 minutes instead of about 4-5 minutes), but the run went through.

The output is reasonable (see two regions of the 3D and MIP labeling):

![Screenshot from 2022-07-18 16-50-36](https://user-images.githubusercontent.com/3862206/179538753-62dd899f-497c-4689-82e3-00700e7c1c8c.png)

![Screenshot from 2022-07-18 16-47-56](https://user-images.githubusercontent.com/3862206/179538167-037477cb-c55c-4c81-9247-70a955d21876.png)

**Comment by tcompa** [comment]
The feature is in-place and one example run went through, I'm closing this issue.
Re-open if needed.
