### ISSUE TITLE
Labeling for organoids through Cellpose

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#111]
Here's an issue for discussing organoid labeling.

At the moment tests are performed on wells B/07 and B/11 of the `210305NAR005AAN` dataset. We first run a MIP, and then segment the whole 2D well.

Free parameters include:
* `model_type`, see https://github.com/fractal-analytics-platform/fractal/issues/110;
* `diameter`
* `labeling_level`
* `labeling_channel`
* Possibly the `cellprob_threshold` (currently this is always equal to zero)

Note that all these parameters can be set through the usual parameter files as in https://github.com/fractal-analytics-platform/fractal/issues/109#issuecomment-1186860518 (this is true for the legacy infrastructure which we are currently using).

A quick first test ran with `nuclei` model, `diameter=250` (this is always rescaled when `labeling_level>0`), `labeling_level=2` and `labeling_channel="A04_C01"` (corresponding to DAPI). Runtime was extremely long (~4 hours), but this is probably related to simultaneous running of a 10-well example - as in https://github.com/fractal-analytics-platform/fractal/issues/57#issuecomment-1168597392. Labeling itself (note that it was on level 2) took <4 seconds.

Results below are clearly suboptimal, but that's a good start: 

![Screenshot from 2022-07-19 08-54-25](https://user-images.githubusercontent.com/3862206/179691123-6b51a6ef-be4e-441d-9294-5b9e20373377.png)

Let's report here about other results (possibly with the incoming dataset prepared by @jluethi, which should be more suitable for this test).

**Comment by tcompa** [comment]
These are the two wells, with parameters
```JSON
{
"coarsening_xy": 2,
"labeling_level": 2,
"labeling_channel": "A04_C01",
"diameter_level0": 300.0,
"cellprob_threshold": 0.0,
"model_type": "cyto2"
}
```

![Screenshot from 2022-07-19 13-44-47](https://user-images.githubusercontent.com/3862206/179742780-d52aed19-cf32-4c98-9e30-33b0c92e563a.png)

![Screenshot from 2022-07-19 13-44-21](https://user-images.githubusercontent.com/3862206/179742759-22583dea-c84d-4d95-bfe2-c9b89f9c5618.png)

**Comment by jluethi** [comment]
I think it's looking very promising.
I ran the cyto2 model on `/data/active/fractal/Liberali/20220719_SegmentationTests/day5_ENR` with diameter 1000 and it creates quite nice masks. Dividing a few organoids that are actually one, but all in all very good.

<img width="1486" alt="Screenshot 2022-07-19 at 18 33 12" src="https://user-images.githubusercontent.com/18033446/179803403-74d7abee-333e-4ed6-9b67-2bf03ce858a6.png">
<img width="1486" alt="Screenshot 2022-07-19 at 18 33 27" src="https://user-images.githubusercontent.com/18033446/179803394-38e08310-1cfc-41c5-baef-7910e34d24ce.png">

I will optimize the parameters of the above example and run one more test case. After that, I'd say we can close this issue, segmentation of organoids in 2D looks to work quite well for the initial implementation :)

**Comment by jluethi** [comment]
Ran some more examples of an even denser & larger organoid test set. We can get reasonable initial segmentations and varying the expected diameter has a large effects on the kind of segmentation results we get.

From an architecture level, I'd say we have what we need to segment organoids at the whole well level. Now it's a question of parameter tuning and potentially retraining some networks (which would then require the ability to take a manually trained network as an input, but let's deal with this when we have one).

DAPI image:
<img width="1837" alt="Organoids_DAPI" src="https://user-images.githubusercontent.com/18033446/180009084-1c06a0af-97cf-4002-9f1d-6ccd8fac5510.png">

Segmentation will diameter 1000:
<img width="1837" alt="Organoids_d1000" src="https://user-images.githubusercontent.com/18033446/180009140-e10897b4-676c-4297-9033-1bd0825aecfb.png">

Segmentation with diameter 2000:
<img width="1837" alt="Organoids_d2000" src="https://user-images.githubusercontent.com/18033446/180009175-5e7182c0-baaf-4c9c-9470-215339262dd9.png">
