### ISSUE TITLE
Generalize Yokogawa filename parsing

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#117]
I received some new test data and noticed that our current filename parsing doesn't generalize for this.

Filenames are:
`220517CS001XXXIl_220715_151525_D05_T0001F001L01A01Z01C04.tif`
`220517CS001XXXIl_220715_151525_D05_T0001F001L01A02Z01C03.tif`
etc.

It then parses potential channel names like:
`'A04_CS001XXXIl_220715_151525_D07_T0001F023L01A04Z20C01'`

(instead of `A04_C01`)

I will look into our current parsing and see if this is an additional input case or just a naming convention the current regex doesn't handle well.

**Comment by tcompa** [comment]
I think it's because of the other `C` in the name, which can be fixed quickly (by also making it more robust).

**Comment by tcompa** [comment]
This should be fixed now, and I also ported it to the `tasks` branch.

**Comment by jluethi** [comment]
Great, thanks a lot for the quick fix, that solves this issue! :)
