### ISSUE TITLE
Use ID instead of name, and add `--id_only` options

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#156]
Right now, client commands require the {task,project,dataset} name, rather than its ID. This was done to have simple bash scripts of CLI calls, but it may introduce constraints on the uniqueness of names, on top of requiring more server calls to convert the names to IDs.

Solution 1 (recommended):
Let's switch back to client taking IDs as arguments, and let's add a `--id_only` flag when appropriate. This flag is such that the client command only output the IDs of the created {task,project,dataset}, so that it is easy to use this ID in a bash script.

Solution 2 (valid but discarded):
Let's have a cache file, locally in the user folder, which contains the mapping of names to IDs. This cache must be updated after most server calls, and it can be used to convert names to IDs without server calls.

**Comment by jluethi** [comment]
Let's discuss this on Wednesday. I'd have some concerns from the user experience side of requiring IDs if someone uses the fractal client interactively. While yes, it can be annoying to specify {task,project,dataset} names, those may mean something to the user, while needing to have 3 different IDs may be harder.
Of course, enforcing the uniqueness may also not be desirable, so let's discuss how we could handle this.

**Comment by jacopo-exact** [comment]
closed in dev
