### ISSUE TITLE
Commit test dataset with real images

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#163]
From time to time, we create fake dataset including just a bunch (say 10-20) of real images from one of the Cardio sets, for testing purposes. Other tests run on (even smaller) fake images which are available in `examples/data/png`.

I'd like to create a folder (probably in `examples/data/`) with actual images and correct mlf/mrf files.

I already have such a folder, locally, and I can push it if @jluethi is OK with that. Its size is a bit too large (240M), but that corresponds to 10 Z planes and 2x2 FOVs. By reducing it to 2 Z planes and 2x1 FOVs, it would take 24 M - which I think is acceptable to have on the repo.

**Comment by jluethi** [comment]
24 MB is still quite large for a git repo. But sure, we can have it in example data. And I'm fine with using some subsets of the cardiomyocyte test sets. Let's use reasonable images though. That would be, middle of the Z stack, not the first image in the stack. Then we can also use it for some demos later & the images will make sense to people looking at them, segmentation would produce somewhat reasonable results etc.

**Comment by jluethi** [comment]
No expert in that either, more a bit reluctant to have the git clone take too long. But 24MB is ok.

We don't have any official sharing setups, I just used e.g. files stored in Google Drive. There are official setups we could go through, but I'm not familiar with them yet. I'll ask at today's napari community call what people are using and if there's an easy way to do this for small test datasets :)

**Comment by jluethi** [comment]
About using a public place to store the example data: Zenodo comes up a lot as a place people are using. Has the very nice benefit of getting a DOI so we can reference the example data. And sounds like a useful thing to do so we can easily provide some example data, both for testing and for demos to potential users! :)

There apparently is a ~50 GB limit, but that means we could easily put e.g. a tiny dataset there, as well as the 2x2 example and potentially even something bigger once we want to. And sounds like Zenodo is very reliable for people using it so far.

I'd be very motivated to put some of my example data on there to make it accessible for sharing :)

Also, people at the napari community call pointed out this really cool REST API to then get the data from zenodo directly via python: https://developers.zenodo.org/#rest-api

**Comment by tcompa** [comment]
You're right, Zenodo looks like a good option.

This is not highest-priority, but I do think that having a couple of (persistent) datasets available over there will be great both for some more serious testing (we can then setup a category of integration tests marked with `long`, which we can skip in github CI and only run from time to time on our clusters) and for showcasing/advertising.

I was not aware of the REST API, but at the moment it seems that it concerns uploading rather than downloading. Luckily the latter is easy to achieve with standard tools. We have multiple options, see a couple of examples below. I think option 1 (with hard-coded links) would probably be a good starting point.

### Option 1: direct links + wget

We can just hard-code the relevant link, and use [wget](https://pypi.org/project/wget/) (warning: this is not mantained since 2015, but I guess we can find a more recent alternative).

```python
import wget

url = "https://zenodo.org/record/6534224/files/multipartite.zip?download=1"
wget.download(url)
```

### Option 2: with pyzenodo3 + wget (+zipfile, to make a complete example)
We get a finer access via [pyzenodo3](https://pypi.org/project/pyzenodo3/), and then again wget+zipfile.
```python
from pathlib import Path
import pyzenodo3
import wget
import os
import zipfile

zen = pyzenodo3.Zenodo()
records = zen.search("tcompa")
for r in records:
    url = r.data['files'][0]['links']['self']
    filename = Path(url).name
    dirname = Path(filename).with_suffix("")
    if not (os.path.isfile(filename) and os.path.isdir(dirname)):
        print(f"Fetching {url}")
        wget.download(url)
        print()
        with zipfile.ZipFile(filename, "r") as zip_ref:
            zip_ref.extractall(dirname)
        print(f"Unzipped {filename} to {dirname}")
    else:
        print(f"{filename} and {dirname} already exist, skip")
    print()
```

**Comment by tcompa** [comment]
Superseded by https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/29
