### ISSUE TITLE
Port measurement task to new architecture

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#164]

**Comment by tcompa** [comment]
As of https://github.com/fractal-analytics-platform/fractal/commit/4fc472746d2d23a37f986ff78b23b85ac098d2cd, we have two working python (non-fractal) pipelines in `tasks/Sandbox_measurement`. Output tables can be inspected with `look_at_2D_output.py` and `look_at_3D_output.py`:
```
$ poetry run python look_at_2D_output.py
/data/active/fractal/tests/Temporary_data_UZH_1_well_2x2_sites/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/tables/nuclei
look_at_2D_output.py:16 <module>
    adata: (
        AnnData object with n_obs × n_vars = 2914 × 8
            obs: 'label'
    ) (AnnData) len=2914

look_at_2D_output.py:18 <module>
    adata.var: <DataFrame({
    })> (DataFrame) len=8

look_at_2D_output.py:20 <module>
    type(adata.obs): <class 'pandas.core.frame.DataFrame'> (type)

look_at_2D_output.py:22 <module>
    adata.obs.dtypes: <Series({
        'label': dtype('O'),
    })> (Series) len=1

look_at_2D_output.py:24 <module>
    num_labels: 2914 (int)

################

$ poetry run python look_at_3D_output.py
/data/active/fractal/tests/Temporary_data_UZH_1_well_2x2_sites/20200812-CardiomyocyteDifferentiation14-Cycle1.zarr/B/03/0/tables/nuclei
look_at_3D_output.py:16 <module>
    adata: AnnData object with n_obs × n_vars = 3694 × 8 (AnnData) len=3694

look_at_3D_output.py:18 <module>
    adata.var: <DataFrame({
    })> (DataFrame) len=8

look_at_3D_output.py:20 <module>
    type(adata.obs): <class 'pandas.core.frame.DataFrame'> (type)

look_at_3D_output.py:22 <module>
    adata.obs.dtypes: <Series({
    })> (Series) len=0

look_at_3D_output.py:24 <module>
    num_labels: 3694 (int)


All looks good, now we just lack an example of running `measurement` through the server.

**Comment by tcompa** [comment]
As of https://github.com/fractal-analytics-platform/fractal/commit/0974c5c9009ecb9e47657fcdf7f2933d436ba64f, we have at least one example of how to run the measurement task as part of a fractal workflow.
Since it acts on a dummy dataset, there actually 0 labels and then measurement is not meaningful. Still, it produces the correct `nuclei` table, with the correct `var`'s but with zero `obs`'s.

Together with the (more meaningful) output of the previous comment, this is sufficient to say that the measurement task is now integrated into fractal. I'm closing this issue. Please re-open it only for urgent/serious problems, or open other issues for glitches or required improvements.

**Comment by jluethi** [comment]
Sounds great! Will test this later with some real datasets and would open new issues if something comes up.
