### ISSUE TITLE
Initial colleciton task - checking for tasks already previously completed

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal#17]
Workflows should created standardized output folders with specific naming conventions. This way, is a user reruns e.g. a compression task and luigi finds the folder called e.g. "COMPRESSED_INPUT", it will just not redo the task, report that it is complete, and carry on with the subsequent dependencies.

Question is: should we check just for the folder name, or also check for existent files inside the folder? To save time, no need to explicitly go over all files as in performing some kind of checksum or  etc, just a quick check.

**Comment by jacopo-exact** [comment]
this issue is superseded by #68
