### ISSUE TITLE
fractal repo should only contain client and common components

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#183]
ref #182

**Comment by jluethi** [comment]
@jacopo-exact Which repo contains the examples? Currently, the examples have been removed from all the main branches across all 3 repositories.

I'd argue for the main fractal repository (this one) to contain the example code, in partial reversal of https://github.com/fractal-analytics-platform/fractal/pull/185/commits/3c02d3876c3a35cc4cb77b681a6bddaad2bffac8 .
Or is there another place where we think the examples should go? They are very valuable to understand how to use the client and can serve as templates for users, so they would fit well into the main fractal repository.

**Comment by jluethi** [comment]
Conclusion from today's call: Let's add some examples of how to use the client on basic synthetic data and on a small public, real dataset as part of the client (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/29).
These examples don't need to cover all possible pipelines that could be run, the task repo (https://github.com/fractal-analytics-platform/fractal-tasks-core) will contain more details examples of running the different tasks on real data.

Such an example will also be the core part needed for the planned Fractal demo.

This issue has a corresponding issue here about ensuring things run: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/30
Once things run & we have an example in this repo, this issue can be closed.

**Comment by tcompa** [comment]
This example now exists in the `dev` branch, as of https://github.com/fractal-analytics-platform/fractal/pull/198.
The issue will be closed when merging into `main`.
