### ISSUE TITLE
Make client easier to install & invoke for users

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#187]
Currently, the client is installed via poetry and then invoked via `poetry run client dataset  ...`.

Can we:
1) Make it easy to install by users by eventually having it pip installable (e.g. from the repo and eventually from pypi)?
2) Make it easier to invoke by giving the client a name, e.g. `fractal_client`?

The goal is that we can have simple installation instructions for the client and that users can invoke it easily (e.g. `fractal_client dataset ...`).

Are there strong opinions about how it should be installed or invoked by users?

**Comment by jacopo-exact** [comment]
@jluethi, the `fractal` name is already taken on pypi.org. have you got a preference for a short alternative? In my tests I was using `fractal-ap` for analytics platform.

Once I have the name, I can release the first version of the client to pypi and then users will be able to pip install it.
For how I set thing up, the client CLI can be accessed by simply invoking `fractal`.

**Comment by jluethi** [comment]
How about we go with `fractal-client`?
Because then, we can also have `fractal-tasks` or `fractal-server` later if we also release them to pypi.

There is already a fractal-analysis package, so let's try to stay clear of that naming.

> For how I set thing up, the client CLI can be accessed by simply invoking fractal.

Ah, that's great! :)

**Comment by jacopo-exact** [comment]
> How about we go with `fractal-client`? Because then, we can also have `fractal-tasks` or `fractal-server` later if we also release them to pypi.

ok, package name: `fractal-client`

**Comment by jacopo-exact** [comment]
https://pypi.org/project/fractal-client/

**Comment by jluethi** [comment]
Awesome, thanks @jacopo-exact ! 👏🏻
