### ISSUE TITLE
client test example

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#189]
test the fractal client with pytest

**Comment by mfranzon** [comment]
Some references regarding asyncclick testing:

Testing asyncclick.CliRunner :
[https://github.com/python-trio/asyncclick/blob/main/tests/test_testing.py](https://github.com/python-trio/asyncclick/blob/main/tests/test_testing.py)

Similar case solved on SO:
[https://stackoverflow.com/questions/67558717/how-can-i-test-async-click-commands-from-an-async-pytest-function](https://stackoverflow.com/questions/67558717/how-can-i-test-async-click-commands-from-an-async-pytest-function)
