### ISSUE TITLE
Improve & centralize feedback to the user whether a pipeline runs through successfully

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#19]
There should be a central place where the user can see whether everything ran successfully and have an easy way to access the error messages if it did not. One example where this still fails:
I submit a job using the apply.json file. I get:
```===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 ran successfully:
    - 1 ConversionTaskWrap(...)
    - 1 WorkflowTask(...)

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====
```

But the actual task then failed to run and the slurm_number.out file contains an error message (e.g. this):
```
slurmstepd: Job 9006803 exceeded virtual memory limit (138640 > 31027), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 9006803 ON pelkmanslab-slurm-worker-004 CANCELLED AT 2022-04-04T14:29:27 ***
```

Would be great if there is a central place that reports that one job failed and then has a way to point the user to the relevant log. Especially once we may have dozens or hundreds of jobs, the user does not want to look through all of them to see if one failed.

Big picture: Just because a Luigi Task can be submitted to the cluster doesn't mean it will run through successfully. Is that reported back to Luigi, e.g. 1 task failed? Is there a way for luigi to then report this to the user?

**Comment by tcompa** [comment]
I am closing at least this issue, since we already have:
* https://github.com/fractal-analytics-platform/fractal/issues/263
* https://github.com/fractal-analytics-platform/fractal/issues/224
