### ISSUE TITLE
client should instantiate one and only one httpclient, auth

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#194]
the client should only open one httpx.AsyncClient and reuse until the end of the lifecycle. Same applies for the Auth object.

This could be implemented using [context](https://click.palletsprojects.com/en/8.1.x/commands/#nested-handling-and-contexts) or, probably even better, [decorating](https://click.palletsprojects.com/en/8.1.x/commands/#decorating-commands) commands with a custom decorator that kind of mimics a context manager, making sure to close the session at the end of the lifecycle.

**Comment by mfranzon** [comment]
Should be fix in dev branch, commit 77eb93b7fa6532debcc0be157ed159bcec9352b0

**Comment by tcompa** [comment]
This will be closed when merging https://github.com/fractal-analytics-platform/fractal/pull/199
