### ISSUE TITLE
Dependency on fractal-server & fractal-tasks-core

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#204]
Should the main repo have dependencies on fractal-server & fractal-tasks-core?

I see the convenience for just installing one repo for tests. But if people should use this to just install the client, they don't also need to install the server & the core tasks locally.

At least when I run `poetry install` on the current main of fractal, fractal-server & fractal-tasks-core are also installed, as far as I can tell the latest releases from pypi.

**Comment by tcompa** [comment]
In this (`fractal`) repo, the `fractal-server` package is only required within the `[tool.poetry.group.dev.dependencies]` poetry group. This means it can be readily skipped by using
```
poetry install --without dev
```
which only installs the package with its dependencies (and not its "development" dependencies).

This way one can have any version of `fractal-server` installed, and installing `fractal` won't change that.

**Comment by jacopo-exact** [comment]
the client should not depend on server nor tasks.

For testing purposes, it dev-depends on fractal-server (without tasks).
It could be added as extra, but I wold rather not, as it would create a circular dependency (server depends on client via common). We could avoid this by introducing a separate fractal-common package, which sounds a bit like overkill for just a few schemas.

closing
