### ISSUE TITLE
Fractal Monitoring Overview

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#224]
Overview issue to discuss monitoring of Fractal.

The issue:
Once a job is submitted by the client, where does the user get feedback?
Is the job still running?
If it stopped: did it finish successfully or did it hit an error?

If it hit an error: Where was the error? Currently, there are different logs (see https://github.com/fractal-analytics-platform/fractal-server/issues/52). Which one is relevant for the user and how do we expose it to the user?

Also, can we see how the resource usage of a job is (are we close to the memory limit or did we use way too much memory / too many core for a given job?) => Can we use `parsl-visualize` for this? First impression is no, as all workflows would be intermixed. But let's have a closer look at this.

Also an issue for the web interface later :)

**Comment by tcompa** [comment]
Concerning "how to retrieve information from parsl monitoring database", there is an example in parsl tutorial notebook number 2 (see http://parsl-project.org/binder). See section `5) Monitoring` and subsection `Accessing monitoring data`.

![Screenshot from 2022-09-16 09-23-38](https://user-images.githubusercontent.com/3862206/190580689-6639a6bb-c648-4b19-a88b-fe24261ecc14.png)

**Comment by tcompa** [comment]
Closing in favor of:
* https://github.com/fractal-analytics-platform/fractal/issues/263 (client side)
* https://github.com/fractal-analytics-platform/fractal-server/issues/52#issuecomment-1268166445 (server side)
