### ISSUE TITLE
Consistent use of `__VERSION__`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#237]
After https://github.com/fractal-analytics-platform/fractal-server/pull/56, we should:
- [x] Update `test_client.py` (or whatever name it will take after https://github.com/fractal-analytics-platform/fractal/pull/236).
- [x] Move `__VERSION__` in `__init__.py`, as in the server.
- [x] Update the bumpver config (in `pyproject.toml`).

**Comment by jacopo-exact** [comment]
closed in dev
