### ISSUE TITLE
Review `expired` in `authclient`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#279]
Very rough description of a behavior I found:
I start the server, register as a user (`curl ...`), run some client command, kill the server, re-start the server, register as a user, run some client command, and I get an `Unauthorized` error.
Our guess, with @mfranzon, is that the `expired` method in `AuthToken` is not sufficiently aggressive.

I will come up with a reproducible example/test first, then we can see how to proceed.

**Comment by jacopo-exact** [comment]
the issue is with the server creating a new secret to sign the token with. I don't think the client should bother with this extremely edge case, as we assume that the server has a much longer lifetime than the client.

**Comment by tcompa** [comment]
Thanks for the clarification. Closing.
