### ISSUE TITLE
Joker step function for saving intermediate outputs

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal#29]
Depending on the workflow at hand, and also for sanity checks and debugging, it is wise to have a step function which can save intermediate outputs. As a simple example, if a .zarr file gets processed through a certain number of steps (as for instance having its images compressed and then multiplied by an illumination correction matrix presented in issues #28 and #26 respectively ), we can save the intermediate output from compression as intermediate output and the compressed+illumination corrected as a final one.

Generally speaking, since this function should be general for almost all steps, should it be called from within a certain task/step as e.g. a boolean?

**Comment by jluethi** [comment]
This will be achieved through defining intermediate steps of napari workflows as outputs as well and being flexible to save multiple outputs. See here for the details: https://github.com/fractal-analytics-platform/fractal/issues/119
