### ISSUE TITLE
`fractal workflow job-status` error log formatting

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#364]
When there is an error in a task, the output of `fractal workflow job-status` is formatted in a way that makes it fairly hard to read the log. Also, I'm not fully sure whether the log is always displayed completely & in the correct order (to be verified).

Would be good to find a way to make the log display more readable.

**Comment by jluethi** [comment]
![Screenshot 2022-12-15 at 16 31 32](https://user-images.githubusercontent.com/18033446/207901372-0773cfea-b7da-4f06-892c-b61f72dcb97c.png)

Here's an example of how those logs can look like

**Comment by tcompa** [comment]
A work-in-progress implementation would expose the `--separate-log`, and for instance `fractal workflow job-status --job-id 123 --separate-log` would give an output like:
```
{
  "project_id": 1,
  "input_dataset_id": 1,
  "output_dataset_id": 2,
  "workflow_id": 1,
  "overwrite_input": false,
  "worker_init": null,
  "working_dir": "/tmp/pytest-of-tommaso/pytest-88/test_workflow_apply0/FRACTAL_RUNNER_WORKING_BASE_DIR/workflow_000001_job_000002",
  "id": 2,
  "start_timestamp": "2022-12-20 13:17:13.208063",
  "status": "failed",
  "history": [
    "dummy"
  ]
}

This is the job log:

TASK ERROR:Task id: 2 (dummy), e.workflow_task_order=1
TRACEBACK:
INFO:__main__:ENTERING dummy task
Traceback (most recent call last):
  File "/tmp/pytest-of-tommaso/pytest-88/test_workflow_apply0/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_dummy0.1.0/venv/lib/python3.10/site-packages/fractal_tasks_dummy/dummy.py", line 150, in <module>
    metadata_update = dummy(**task_args.dict())
  File "/tmp/pytest-of-tommaso/pytest-88/test_workflow_apply0/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_dummy0.1.0/venv/lib/python3.10/site-packages/fractal_tasks_dummy/dummy.py", line 71, in dummy
    raise ValueError(message)
ValueError: default message
```

Would this formatting be enough for improved clarity?

**Comment by tcompa** [comment]
> I'm not fully sure whether the log is always displayed completely & in the correct order (to be verified).

It'd be good to know, please open an issue if you see some inconsistencies.
Also note that at the moment we are only populating the `log` field when the job fails, and not when it is successful.

**Comment by jluethi** [comment]
> It'd be good to know, please open an issue if you see any inconsistency.

I think that was the part of some log messages getting cut off due to the multiple processes running on the same node. I'd open a new issue if I can reproduce this again.

> Would this formatting be enough for improved clarity?

This formatting looks much more readable and will be very useful! 
Can we make it the default for failed workflows? Fine with having a flag to change the behavior, but the default thing a user should see in case of a failed workflow is the way it's printed above. This is useful and focuses the user on the actual error message. It also makes it easier for them to copy an error message & send it to us for debugging.

**Comment by tcompa** [comment]
>  Can we make it the default for failed workflows? Fine with having a flag to change the behavior, but the default thing a user should see in case of a failed workflow is the way it's printed above. This is useful and focuses the user on the actual error message. It also makes it easier for them to copy an error message & send it to us for debugging.

As part of #367, there are now two behaviors:
1. If `job.log` is `None` or if one adds the flag `--do-not-separate-logs`, then one obtains the standard behavior (logs as a single string encapsulated in the job object).
2. If `job.log` has some content and one does not add the flag `--do-not-separate-logs`, then one obtains the "prettier" format.

**Comment by jluethi** [comment]
Awesome, thanks @tcompa !
