### ISSUE TITLE
Making fractal client less verbose by default

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#374]
Currently, using the example scripts is very verbose. We get all of the debug messages as well as the full workflow after every task that was added with `fractal workflow add-task`.

Can we make the client less verbose by default? e.g. by default if only returns INFO & above (and if a user adds a -vv flag, it also gives the debug => this already seems possible according to the help message of the client). Would this change if I mess with the logging level server side, i.e. if I decrease/increase this, then would that affect whether the client prints DEBUG messages by default? Or is this a client-side setting?

And can we turn off the default printing of the full workflow after every `fractal workflow add-task`? The example scripts contain a `fractal workflow show $WF_ID`, which would then show the final output once. Currently, when adding 8 tasks, I get 8 (increasingly long) workflows printed to the console.

**Comment by tcompa** [comment]
A few upcoming changes in PR #377:

## --verbose flag
```
$ poetry run fractal
usage: fractal [-h] [-u USER] [-p PASSWORD] [-s SLURM_USER] [--verbose] [--batch] [-j] {register,project,dataset,task,workflow,job,version} ...

Client component of Fractal

options:
[...]
  --verbose, -v         Change minimal logging level from default to DEBUG
[...]
```

## Default logging level
If `--verbose` is not included, the default logging level is used. This is `20` by default, and it can be overridden by the env variable `FRACTAL_LOGGING_LEVEL` (to be specified as an integer, see https://docs.python.org/3/library/logging.html#logging-levels).

> Would this change if I mess with the logging level server side, i.e. if I decrease/increase this, then would that affect whether the client prints DEBUG messages by default? Or is this a client-side setting?

This is fully a client-side setting.

## Output of `workflow add-task`

We added a `--batch` option, like in several other commands, which reduces the output size. Actually it gives no output at all, at the moment, but this could/should change if we update the server as in https://github.com/fractal-analytics-platform/fractal-server/issues/400 - then we would just print the id of the new workflow task.

**Comment by tcompa** [comment]
I'm merging #377 and closing this for now. Please @jluethi check if you need something else and re-open this one or open another issue.

Note that [I've added the `--batch` option in the 01 example in fractal-demos](https://github.com/fractal-analytics-platform/fractal-demos/commit/6e643533999825429d66866b8dd2e6eda768fc3d). If this is too cumbersome, we'll update the client further.

**Comment by tcompa** [comment]
Some more info:

As of #394 (and related server updates), the `workflow add-task` only returns the newly created WorkflowTask, instead of the whole updated Workflow. Therefore we could streamline the client output, which now is:
* With `--batch`, only output the new-WorkflowTask ID
* Without `--batch`, output the whole WorkflowTask object

Since this is clearly less verbose than the previous version, I removed the `--batch` option from the example in `https://github.com/fractal-analytics-platform/fractal-demos/blob/main/examples-v1/01_cardio_tiny_dataset/run_example.sh`.
