### ISSUE TITLE
New `fractal workflow {import,export}` commands

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#425]
As of https://github.com/fractal-analytics-platform/fractal-server/pull/490, the server has new endpoints to import/export a workflow.

The new client commands should look like:
* `fractal workflow import --json-file /some/file.json`, which would first cast the content of `/some/file.json` to a `WorkflowImport` object and then call the appropriate endpoint.
* `fractal workflow export workflow_id --json-file /some/file.json`, which would call the endpoint to export the workflow with ID `workflow_id` and store the output in `/some/file.json`.

Notice that [we also need to update fractal-common](https://github.com/fractal-analytics-platform/fractal-server/pull/490#issuecomment-1420806486), and obviously to install the right version of fractal-server (will be released soon enough).

**Comment by jluethi** [comment]
The second command should be `fractal workflow export workflow_id`, right?

**Comment by tcompa** [comment]
> The second command should be `fractal workflow export workflow_id`, right?

Sure, thanks
