### ISSUE TITLE
Improve interactive OME-Zarr viewing performance in napari

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#45]
Loading large, multi-well OME-Zarr projects into napari and browsing them interactively is still on the slower side. Here is an overview of what we're doing to improve that and what we can still try.

**Things that we have already found to improve this:**
- Setting environmental variable `NAPARI_ASYNC=1` before launching napari: Loading still a bit slow, but interface doesn't freeze while loading
- Having the zarr files use compression (was already on by default), see here: https://github.com/fractal-analytics-platform/mwe_fractal/issues/28

**Things we are working on:**
- Errors thrown about non-existing wells, see issue here: https://github.com/fractal-analytics-platform/mwe_fractal/issues/35
- Having more pyramid levels, see here: https://github.com/fractal-analytics-platform/mwe_fractal/issues/32. Currently, our lowest-resolution pyramid-level is still 1215 x 1280 per well. Looking at some example datasets, e.g. [this one from the ome developers](https://hms-dbmi.github.io/vizarr/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/idr0094A/7751.zarr), they have pyramid levels as small as 67x67 per site (also sites saved individually, see below in Zarr organisation) => This currently doesn't help at all, investigating

**Remaining issues:**
- What pyramids are loaded when. During initial loading, the full resolution tile seems to be loaded (to calculate rescaling parameters maybe?). See here for the logs: https://github.com/fractal-analytics-platform/mwe_fractal/issues/35. Also, while browsing, napari sometimes quickly switches between two pyramid levels (e.g. between level 3 & 4).
- The "aggressiveness" of napari loading new pyramid levels is also mentioned by the napari-ome-zarr plugin devs here: https://github.com/ome/ome-zarr-py/pull/195

**Potentially contributing:**
- The Zarr organisation: Do we split multiple field of views or save all fields of view of a well as a single field of view, see here: https://github.com/fractal-analytics-platform/mwe_fractal/issues/36 => Unlikely to be an issue. According to OME devs, our implementation may actually a bit faster, even if it's not fully as intended

**Comment by tcompa** [comment]
Useful refs:
* https://github.com/andy-sweet/napari/blob/55b025a6013f90914f15bca7030aca98ed542b40/docs/naps/4-async-slicing.md
* https://github.com/napari/napari/pull/4905

**Comment by jluethi** [comment]
Yes, the PR implementing these changes improves visualization performance quite a bit. It doesn't change the actual loading speeds that much, but makes the interface fully responsive during all movement and thus improves the experience of browsing the dataset. Had a few rounds of tests & improvements with Andy Sweets to get rid of some bugs, very optimistic about this implementation now.
See here: https://github.com/napari/napari/pull/4905

I think it's worth using that PR when we want to test performance and it may make for better demos :)

I'd say we can close this for the time being. Let's wait for the PR to make its way into napari and for sharding to come to Zarr to improve the performance further :)
https://forum.image.sc/t/storing-large-ome-zarr-files-file-numbers-sharding-best-practices/70038
