### ISSUE TITLE
Parsing metadata from Yokogawa experiments

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal#46]
Any experiments coming from the Yokogawa microscope generate a couple of metadata files (with `.mrf` and `.mlf` extensions).

You can find information on how this is being parsed by Drogon [here](https://github.com/fmi-basel/job-system-workflows/blob/28f4c45b17aa96d552d528ef6328737d059ae8a9/src/gliberal_workflows/tasks/yokogawa_image_collection_task/versions/version_0_5.py#L85). The corresponding empty dataframes for each meta file are created just before this line.

Proper parsing of metadata is important not only for being able to potentially save it (within?/alongisde?) .zarr output for further reference but also for processing steps such as #23 where we need the positional information of each recorded field.

**Comment by tcompa** [comment]
Closing this, moving to
* https://github.com/fractal-analytics-platform/fractal/issues/112
* https://github.com/fractal-analytics-platform/fractal/issues/113
* https://github.com/fractal-analytics-platform/fractal/issues/114
* https://github.com/fractal-analytics-platform/fractal/issues/115

**Comment by jluethi** [comment]
The updated table looks like this:
![Screenshot 2022-07-21 at 17 11 33](https://user-images.githubusercontent.com/18033446/180249169-a4065454-1c52-41fa-8781-8e7657338208.png)

=> added columns for x, y & z pixel, thus the metadata now also specifies the dimensions in pixels for each field of view, which is required to specify regions of interest.

**Comment by jluethi** [comment]
The metadata table can optionally contain a time column:
<img width="1135" alt="20220803_metadata_table" src="https://user-images.githubusercontent.com/18033446/182591157-7caa225e-0c1b-4166-b479-6189ad77b340.png">
