### ISSUE TITLE
Expose `pinned_package_versions` in `task collect`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#507]
This requires
* https://github.com/fractal-analytics-platform/fractal-server/issues/740
* https://github.com/fractal-analytics-platform/fractal-server/pull/744

---

In principle `pinned_package_versions` could be a dictionary with multiple entries, like
```json
{
"pkg1": "1.0.0",
"pkg2": "1.2.3",
}
```
but I think that for the CLI client we  can start by only allowing a single package version to be pinned.

In that case, the argparse interface could look like
```
fractal task collect [-h] [--python-version PYTHON_VERSION]
                     [--package-version PACKAGE_VERSION]
                     [--package-extras PACKAGE_EXTRAS]
                     [--pinned-dependency PINNED_DEPENDENCY]
                     package
```
with, for instance, `PINNED_DEPENDENCY="torch=1.12.1"`.

Note that we could find other solutions to be more flexible and allow multiple dependencies, e.g.
1. A `--pinned-dependencies-file /some/file.json` argument, so that we can pass a rich dictionary with multiple pinned versions;
2. Some rule that allows to quickly parse an argument like `PINNED_DEPENDENCIES="torch=1.12,pydantic=1.0".
3. An actual `json.dumps/json.loads` logic, so that we can pass something like `--pinned-dependencies '{"torch": "1.12", "pydantic": "1"}' (I don't like this solution, because it will always creates a mess with quotes and escaping).

I think this is not relevant for the planned use case (which is essentially "install some older torch version"), but there would be no problem in implementing 1 or 2 if it seems useful (@jluethi?).

**Comment by jluethi** [comment]
That's great!

Yes, we only need it for torch at the moment. But if we can make 2 work, we'd be flexible if things come up in the future. I'd assume implementing 2 is not a major effort? If so, let's include this here.

**Comment by ychiucco** [comment]
To get multiple pinned versions we cal also use `action="append"` from argparse (https://docs.python.org/3/library/argparse.html#action)

```console
fractal task collect ... --pinned-dependency 'torch=1.12.1' --pinned-dependency 'pygment=2.0'
```
