### ISSUE TITLE
Task performances within/without parsl

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#57]
This is a discussion issue to monitor our improved understanding of what's going on within parsl, and on how it manages the resources to assign to each task. More on this later.

**Comment by tcompa** [comment]
> One last bit of information, again as a reference for future tests.
> 
> For the test in [#57 (comment)](https://github.com/fractal-analytics-platform/fractal/issues/57#issuecomment-1161390444), I re-ran the MIP part alone in a SLURM job (without parsl, and with `--cpus-per-task=16`), via this script:
> 
> ```
> #!/bin/bash
> OLDZARR=/data/active/fractal/tests/Temporary_data_UZH_10_well_5x5_sites/20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
> NEWZARR=/data/active/fractal/tests/Temporary_data_UZH_10_well_5x5_sites/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr
> 
> rm -rf $NEWZARR
> 
> WELLS="B/09 B/11 C/08 C/10 D/09 D/11 E/08 E/10 F/09 F/11"
> 
> poetry run python ../../fractal/tasks/replicate_zarr_structure.py \
>                   -zo $OLDZARR \
>                   -zn $NEWZARR \
> 
> echo "[MIP] START"
> date
> for WELL in $WELLS; do
>     echo $WELL
>     time poetry run python ../../fractal/tasks/maximum_intensity_projection.py \
>                            -z ${OLDZARR}/${WELL}/0 \
>                            -cxy 2
> done
> date
> ```
> 
> Note that wells are analyzed one after the other, and not in parallel.
> 
> This test ran in ~13 minutes, that is, ~80 seconds per well (on average). The same MIP processing of the 10 wells takes 248 s per well (on average) when running through parsl. Thus it seems that parsl is adding a `3x` slowdown, for this specific task and dataset.

This should be re-tested in view of https://github.com/fractal-analytics-platform/fractal/issues/92.

**Comment by jluethi** [comment]
The conclusion here is that the limiting factor is disk IO on the Pelkmans lab shares, so Fractal is running as fast as it reasonably can for those tasks.

Thus, let's close this issue related to parsl performance and open new issues regarding IO when they become more urgent.
