### ISSUE TITLE
OME-Zarr parsing has non-deterministic assignments of channels per well

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#61]
The current OME-Zarr parsing has no fixed mapping between the channel name in the original filename (or any channel metadata we may want to include) and the channel number it assigns when parsed to an OME-Zarr file. That leads to the bug where images assigned to channel 1 in well B03 may be from a different channel than images assigned to channel 1 in well C06.

Because channels are displayed as layers in napari, that then leads to a layer containing different information depending on the well, which we need to fix.
See here: The same channel is DAPI (nuclear marker) vs. Lamin B1 (nuclear envelope marker), depending on the well in the 23 well dataset (=> one looks like solid, round objects, the other is more pronounced at the rim of the object).
<img width="1667" alt="Bildschirmfoto 2022-06-01 um 11 57 08" src="https://user-images.githubusercontent.com/18033446/171380318-86c434fe-0213-4d43-9492-1855537df4ed.png">
<img width="1667" alt="Bildschirmfoto 2022-06-01 um 11 56 45" src="https://user-images.githubusercontent.com/18033446/171380340-c772d6e4-cc05-43cd-b16a-4af04697d289.png">

What we would like to achieve:
1) A given channel (e.g. C01) is always parsed to the same channel number in the OME-Zarr file
2) This can get somewhat more complicated down the road: We may have multiple so-called cycles all having channels C01, C02 etc. And users may (but rarely do) acquire multiple C01s in the same cycle, with varying acquisition numbers. E.g. A01_C01, A02_C01 etc.
3) We should parse additional metadata for channels (see also here: https://github.com/fractal-analytics-platform/mwe_fractal/issues/44). I'm currently looking into things like contrast-limits, colormaps and channel naming to see where we would need to place them in the OME-Zarr file and which actually get processed by OME-Zarr so far.

**Comment by tcompa** [comment]
> Note to future self: `true` and `false` are JSON keywords, and writing them from our python script is a bit annoying. We'll start by ignoring `inverted` and `active`, and think about it later.

This was actually much simpler than we thought back then, see
```python
import json
d = {1: True}
with open("/tmp/out.json", "w") as f:
    json.dump(d, f)
```
leads to
```bash
$ cat /tmp/out.json 
{"1": true}
```

We were probably confused by other things, since this is actually trivial (as it should be).
