### ISSUE TITLE
Lazy loading of wells and multi-site plates

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#66]
[not a fractal workflow issue, but we should have a high-level issue to discuss our progress on this]

We want to be able to lazily load single wells, not just whole plates. And we also want to support plates where each well consists of more than a single site (currently all fused into one, see https://github.com/fractal-analytics-platform/mwe_fractal/issues/36).

This is work required on the ome-zarr-py side to allow to load images accordingly. Also, while doing this loading, we'll need to find a place to store well dimensions (e.g. are the sites arranged as 9 by 8 or 8 by 9) somewhere in the OME-Zarr file and read it. See this issue for guidance of how we can implement this: https://github.com/ome/ome-zarr-py/issues/200

**Comment by tcompa** [comment]
I confirm that recent tests of timing on my side (https://github.com/fractal-analytics-platform/fractal/issues/66#issuecomment-1165402480) were performed on MIP zarr files, which (somewhat by accident?) had the correct dtypes (uint16) at all pyramid levels. So https://github.com/fractal-analytics-platform/fractal/issues/92 does not apply to those numbers.

I still have to verify whether file sizes were checked for data with the correct/wrong dtype.
