### ISSUE TITLE
Enable example atomic steps where images are passed in memory

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#76]
We want to build the infrastructure for atomic steps that the user can chain in different ways and change paramters for. A combination of atomic steps then make up a task. But between the steps, processed image data is passed in memory to avoid constant IO.

An example:
A user applies a threshold to an image of a given channel, expands the mask using dilation and then applies a label function.

Threshold function:
```
from skimage.filters import threshold_otsu

def threshold(image):
    thresh = threshold_otsu(image)
    binary = image > thresh
    return binary
```

Expansion function:
```
from skimage.morphology import binary_dilation

def expand_mask(mask, rounds = 3):
    for round in range(rounds):
        mask = binary_dilation(mask)
    return mask
```

Label function:
```
from skimage.measure import label

def label_mask(mask):
    return label(mask)

```

Obviously, those 3 functions could be combined into a single task, but it is hard to foresee all combinations of all those functions users may want to do.
The goal is to have a wrapper for atomic tasks that handles loading of images and then saving of label images (or maybe also feature measurements?). Users can then define the intermediate pipeline, getting e.g. an image (e.g. a single fov), process it with a chain of steps with some parameters (kept those low for the beginning, all those functions could get more parameters) and the result can then be saved again.

**Comment by jluethi** [comment]
I saw a very interesting presentation by Ryan Savill at today's napari CZI accelerator meeting about the napari assistant, basically a way to build image processing workflows in napari. They define dask pipelines for processing the images. May be a very cool framework to build this feature on and allow users to define workflows interactively in the napari-assistant on a small subset of the data, to then take the workflow objects & execute them on the whole dataset :)
Here's the napari assistant: https://github.com/haesleinhuepf/napari-assistant 

I'll be evaluating this more next week to figure out whether this could be a good framework to rely on

**Comment by tcompa** [comment]
As of yesterday's call, we agreed to postpone this discussion. In principle the incoming server-based architecture should be such that this feature can be introduced, but first it is interesting to further explore an "integration" of napari-assistant.

The idea we discussed is something on this line:
1. The user plays with napari-assistant (outside Fractal), constructing chains of image-processing operations and finding some good parameters.
2. At the end of this part, the user retrieves the final Python code corresponding to the whole processing chain.
3. This code goes becomes a single function `processing(img, **kwargs)`, which the user copy-pastes into a template of a Fractal task.
4. The pre-written template takes care of loading a zarr array (corresponding to a whole well, for instance), mapping `processing` onto all relevant parts of the array (this could be images, FOVs, ROIs, ...) and storing the output.

If we find that the napari-assistant steps are sufficiently stable (and the final Python code is easy to retrieve), we may avoid including this additional complexity (i.e. having some tasks which correspond to a chain of steps only acting in memory, without I/O - apart from the first/last ones) into Fractal.

More general comment: having such a template would be useful in general, also if the `processing` function comes from other sources.

**Comment by jluethi** [comment]
I tested the napari assistant today and it looks quite promising. I can define a workflow in napari interactively and then export it as a yaml file. I created an example workflow that does decent nuclear segmentation on a DAPI image (not quite as good as cellpose, but nice that we can get there with classical tools): Smooth image, apply [voronoi otsu labeling](https://clij.github.io/clij2-docs/reference_voronoiOtsuLabeling) and expansion (not necessary, just to test that we can modify labels.

It can then be applied to new images in Python easily:

```
from napari_workflows import Workflow
from napari_workflows._io_yaml_v1 import load_workflow, save_workflow
import numpy as np
import imageio

# load workflow
workflow_filename = 'wf_smooth_voronoi_label_expand.yaml'
napari_workflow = load_workflow(workflow_filename)

# Get input image
input_path = 'path/to/img'
input_img = imageio.v2.imread(input_path)

# Run workflow
napari_workflow.set("input", input_img)
output_label_img = napari_workflow.get('Result of Expand labels (scikit-image, nsbatwm)')

```

So in very simple code, we can call potentially quite complex workflows.



There are still a list of issues though which I'll open in the relevant repositories and link to here so we can track the progress. Mainly, those are:
1. Flexibility of input definition, how do we know how to define the input image
2. Flexibility of output, making it more generic
3. Including measurements into this workflow: The fundamentals for this are there, could be used for https://github.com/fractal-analytics-platform/fractal/issues/69. e.g. using [napari-regionprops](https://www.napari-hub.org/plugins/napari-skimage-regionprops). But it currently doesn't seem to work in the napari assistant to become part of the workflows.

Also, there are a series of smaller bugs and instabilities to follow up on.

In general though, it's very promising how easy a pipeline is defined, I could run my example pipeline here that was created on a 2D image also successfully on 3D images and it's really easy to apply it in Python! :)

Also, here is my example pipeline (saved as .txt instead of .yaml, because github doesn't support uploading yaml files)

[wf_smooth_voronoi_label_expand.txt](https://github.com/fractal-analytics-platform/fractal/files/9159543/wf_smooth_voronoi_label_expand.txt)

**Comment by jluethi** [comment]
Ok, I've been digging a bit further and this should really work! :)

We can use the example workflow above (just rename the [wf_smooth_voronoi_label_expand.txt](https://github.com/fractal-analytics-platform/fractal/files/9159543/wf_smooth_voronoi_label_expand.txt) to `wf_smooth_voronoi_label_expand.yaml`. This generates relevant label images that are decent segmentations. Let's build the Fractal infrastructure that can submit such a workflow and save the resulting label images. With this, we will have support for a broad basis of chained, atomic image processing tools out of the box!

What needs to be done for this implementation:
- A wrapping task that takes the hcs ome-zarr file and the workflow yaml file.
- The wrapping task needs to parallelize over a relevant part (let's start by applying them on ROIs, but it should also be possible to apply them on whole wells eventually)
- We need to define Input(s)/Output(s): I think this best goes via dictionaries (though I'm open to better ideas here). A workflow can have multiple inputs and multiple outputs. I will generate a few more workflow examples so we have tests for each (I'll open a new issue for this so we have an overview of what workflows we want to support initially, TBD). In the above case, we'd have a single input that I renamed to "input", though those inputs can have arbitrary names in the pipeline. The main output of the workflow is `Result of Expand labels (scikit-image, nsbatwm)`, but `Result of Voronoi-Otsu-labeling (nsbatwm)` is a valid output as well. Both are label images that we could save. Details in upcoming issue :)
- We need to handle saving the label image(s) generated by the workflow to the correct place in the OME-Zarr file. Maybe needs to include a type check for what kind of output is generated (see #69 for ideas on how we can also use this to generate feature measurements)
- Input/output structure here could be something like:
```
workflow_inputs = {'input': 'DAPI'}  # or whatever way we want to relate to a channel in Fractal
workflow_outputs = {
    'Result of Expand labels (scikit-image, nsbatwm)': 'Expanded Nuclei Labels',
    'Result of Voronoi-Otsu-labeling (nsbatwm)': 'Voronoi Nuclei Labels'
}  # values are how the label outputs would be saved
```


Overall, I think the yaml file structure is alright. But let's collect wishes we'd have for improvements, because this is explicitly `napari_workflows._io_yaml_v1`, so will eventually change. e.g. one issue I'll open is the idea that I'd like to have explicit input & output definition in the file (=> users mark which channels are output, the systems flags input channels => we could then provide a list of inputs & outputs the users need to "connect" to channels

Open questions:
- Dependency handling: I assume we'll need to have all the dependencies installed that we want to be using. For the example we're using here, that's just `napari_segment_blobs_and_things_with_membranes` ([here](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes)) and `napari_workflows` as a base ([here](https://github.com/haesleinhuepf/napari-workflows)). napari workflows would support running functions from diverse libraries though. For an initial implementation, let's just install the dependency libraries needed. Eventually, there is a larger debate on how to handle this to fully generalize & also a debate within napari workflows whether a workflow could also provide a virtual env / a docker container for things to be run in.

**Comment by tcompa** [comment]
We have a first example of wrapping `napari_worfklows` in #69 (for measurement), and we have a more organized discussion of several use cases in #119. This points towards not pursuing the atomic-steps-within-fractal route (at least not now), and I'm in favor of this choice.

@jluethi Do you agree? Can we close this issue?

**Comment by jluethi** [comment]
Great progress! Yes, I added the only remaining details on dependency handling also to #119 . Let's close this and continue work in #119
