### ISSUE TITLE
Single pipeline file (to better define task arguments + to export/reuse a workflow)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#85]
I'm putting this issue here as a placeholder for future discussions.

We should define a structure for encoding as much information as possible about a workflow definition within a single (JSON?) file. This serves at least two goals:
1. We simplify the definition of arguments for tasks, which is currently treated with plenty `if` checks within `fractal_cmd.py` (and this doesn't work for user-defined tasks) -- ref https://github.com/fractal-analytics-platform/mwe_fractal/issues/21.
2. We simplify the replication of a workflow (or its transfer to someone else) - ref https://github.com/fractal-analytics-platform/mwe_fractal/issues/67#issuecomment-1149810478.

There is a current (vague) plan of having a file like:
```
{
"task_name_1": {"numer_of_levels": 4, "some_parameter": [1, 3], slurm_partition="cpu"},
"task_name_2": {"x": "/path/to/zarr", slurm_partition="gpu"}
[...]
}
```
so that the `apply` function in  `fractal_cmd.py` (or its future server-side replacement) receives this file and knows which parameters to use for each task. We need to go through this a bit more carefully, before implementing, to make sure that it doesn't introduce some edge case where things won't work.
Note that (for the moment) this file would not be sufficient to reproduce a full workflow, since it would only know the task parameters. The actual definition of which tasks to include, and in which order, is currently provided e.g. by a bash script in the `examples` folder.

**Comment by jacopo-exact** [comment]
This issue is deprecated in favour of #155.
