### ISSUE TITLE
devise an efficient method for task discovery

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#91]
We need a way, preferably an automatic one, to tell the server which tasks are at its disposal, and to add this information to the central database, to be served to clients. For this reason every task must advertise its inner workings by means of a task manifest. At the very minimum:
```
name: str
input_type: str
output_type: str
```
almost certainly we'll also need a 
```
default_parameters: Dict[str, Any]
```
for all the default parameters required to run the task besides determining input and output.

possible solutions:
1. Add a `__FRACTAL_MANIFEST__: Dict[str, Any]` dunder variable within the task code itself. This is very clean but it requires all the source code to be imported upfront, which can require a few seconds with just a handful of tasks.
2. Place the information in a `<task_name>.fractal` file in a serialised format (json seems the obvious choice) that sits in the same folder (currently `fractal/tasks/`) as the actual code. Then we can simply glob the file pattern and read the info out.
3. have each task reside in a separate folder in which we require a dunder file `__FRACTAL_MANIFEST__` with the same. This is the most future proof option as it would allow to, e..g, clone a repo somewhere, as long as that repo contains the magic file.

For a (small) selection of core tasks we could use option 2, but I strongly advise towards option 3.

**Comment by jluethi** [comment]
Thanks for the overview of the options Jacopo!

From a (power) user perspective, option 2 & 3 are very attractive. It means we can make it fairly easy for users to add new tasks without having to change any of the general files and the core function really is just a python file with a python function, plus there is a small "metadata" file that contains some relevant info. We could also receive python function files from users and just add the metadata file on top easily then.

From a user side, I don't feel like option 2 or 3 would differ that much. So if option 3 seems like the thing that would be more stable long term, let's directly go with that

**Comment by jluethi** [comment]
Conclusion of our call on July 5th was that option 3 seems like a good direction to go, so let's work towards this when we refactor the tasks next :)
