### ISSUE TITLE
MIP after label creation

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#96]
Does the MIP still work for you in workflows that contained the labeling function? I ran the 9x8 example. It seems to have saved the labels. But when I try to open the MIP, the napari plugin fails.
It's a bit suspicious that the MIP appears to have an extra pyramid layer. Maybe the MIP assumed the labels folder was another pyramid layer?
![Screenshot 2022-07-05 at 16 28 52](https://user-images.githubusercontent.com/18033446/177351728-74f53c17-b496-46f9-adfa-3840191f9110.png)
 
Just removing folder 5 from the MIP folder doesn't help though. Maybe the Zarr structure replication needs to start handling labels? We can also do MIPs on labels, that is an approximation of the 2D segmentation, though not always the best (people may want to run specific 2D models) => not sure whether we urgently need the ability to do MIPs on labels. It's a nice to have, but priority would be that labels don't interfere with MIPs :)

**Comment by tcompa** [comment]
The bug is here: https://github.com/fractal-analytics-platform/fractal/blob/main/fractal/tasks/replicate_zarr_structure_mip.py#L47.

(to be fixed a bit later)

**Comment by tcompa** [comment]
In principle this is fixed with https://github.com/fractal-analytics-platform/fractal/commit/ddb5c124d3a93652de984d59e5d8438109f41263. I tried on a small example and it produced a reasonable MIP.

@jluethi: if you have an example where it works, we can close this issue.

**Comment by jluethi** [comment]
Yes, that fixed it! Thanks a lot for the fast bug fix @tcompa ! 👏🏻

Here is an MIP of the 2x2 with labeling as part of the workflow, works again like before :)

<img width="1177" alt="Screenshot 2022-07-07 at 10 03 56" src="https://user-images.githubusercontent.com/18033446/177723519-4b5c5e2a-fc7d-4590-9137-78dd0849acd2.png">
